title: Jethro Elijah Bolima
author:
  name: Jethro Elijah Bolima
  social:
    email: jetbolima@gmail.com
    linkedin_username: jethro-elijah-bolima
    github_username: jetbolima

description: An aspiring data analyst
theme: jekyll-theme-slate



  
footer_text: >
  This portfolio is maintained by [Jethro Elijah Bolima](https://github.com/jetbolima)
  Published with [Github Pages](https://pages.github.com/)

   

