title: Jethro Elijah Bolima
author:
  name: Jethro Elijah Bolima
  email: jetbolima@gmail.com

description: An aspiring data analyst
logo: /assets/img/Profile_Picture.jpg
theme: jekyll-theme-slate

social_links:
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jethro-elijah-bolima" }
  - { platform: github,         user_url: "https://github.com/jetbolima" }
  
footer_text: >
  This portfolio is maintained by [Jethro Elijah Bolima](https://github.com/jetbolima)
  Published with [Github Pages](https://pages.github.com/)

   

